### ISSUE TITLE
Task :buildSrc:compileKotlin FAILED

### ISSUE THREAD

**Issue by mishinivan** [travelpayouts/white-label-app-android#3]
Когда в терминале запускаю команду: 
./gradlew parseConfig

Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target

> Task :buildSrc:compileKotlin FAILED
Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileJava' (22) and 'compileKotlin' (21).

**Comment by tpsupport** [comment]
Здравствуйте,

Для исправления данной ошибки попробуйте, пожалуйста, изменить версию Gradle JDK в настройках Android Studio. Сделать это можно следующим образом:
Android Studio → Settings → Build, Execution, Deployment → Build Tools → Gradle → В окне измените версию Gradle JDK на JDK 21 или ниже.

**Comment by mishinivan** [comment]
Проблема остается, пробовал jdk 21 и ниже выбирать.
 Так же пробовал очищать кэш и перезапуск студии и системы.

**Comment by mishinivan** [comment]
Проблема была в том, что в системе версия java по умолчанию установлена 22, поменял на 21 и все заработало. Изменения в андроид студии на системную версию не влияли.

**Comment by tpsupport** [comment]
Hello,

To resolve the issue kindly select Java version 11 or higher in Android Studio. You can do this by navigating to Settings → Build, Execution, Deployment → Build Tools → Gradle. After updating the Java version, please sync the project again by going to File → Sync Project with Gradle Files. After that, you should see the Build → Generate Signed Bundle/APK option in the menu. 

If you still encounter any issues, please don't hesitate to reach out to us via email at support@travelpayouts.com.
