### ISSUE TITLE
Background Image and Icon Style Changes Not Applied

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-android#5]
Hi,

I followed the instructions to change the background image and icon style, but the changes are not reflected in the application.

I would greatly appreciate any guidance or assistance on how to resolve this issue. Are there any additional steps or configurations I might be missing? Thank you for your support!

**Comment by tpsupport** [comment]
Hello,

Thanks for reaching out!

Kindly specify if you followed these steps:

1. Save the changes to the file.
2. Execute the command ./gradlew parseConfig in the terminal in Android Studio.
JDK must be installed for the correct operation of this command in the Android Studio terminal. If it is not installed automatically with Android Studio, install it independently for the required operating system.
3. Rebuild and run ▶.

In case you did, please provide us with the version and the configuration file of your app? You could find configuration file in `/config/app_config.json`. Also, we'd appreciate the image you've tried to set as a background.

Looking forward to your response.

**Comment by baaguigui** [comment]
Yes, I followed the steps you mentioned:

1. Saved the changes to the `app_config.json` file.
2. Executed the command `./gradlew parseConfig` in the terminal in Android Studio.
3. Ensured that JDK is installed and configured correctly.
4. Rebuilt and ran the application.

![Untitled](https://github.com/travelpayouts/white-label-app-android/assets/65304499/2da20b3c-3cb5-45d7-aa90-ad1d7089a8df)


And this is the image I tried to set as the background.
![backgroundimage](https://github.com/travelpayouts/white-label-app-android/assets/65304499/e6476ae6-9109-4150-a2c0-6bb036d8ece6)

Additionally, I encountered the following error when running the ./gradlew parseConfig command:

`> Task :parseConfig FAILED
Generating advertising config strings.xml... ✅ 
Copying 'google-services.json'...    ✅ 
Generating app_version.properties... ✅ 
Generating handling_link.properties... ✅ 
Generating app name strings.xml... ✅ 
Generating app description strings.xml... ✅ 
Generating partner url strings.xml... ✅ 
Generating google maps strings.xml... ✅ 
Generating 'policy_url.xml'...   ✅ 
Generating colors.xml... ✅ 
Copying custom icons...      ✅ 
Parsing images...      
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':parseConfig'.
> config project not found

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 739ms
5 actionable tasks: 2 executed, 3 up-to-date
`

**Comment by tpsupport** [comment]
Thank you for the provided information!

Could you please send us the configuration file of your app? So that we can check what might have gone wrong.

You can send the file to our support team email: support@travelpayouts.com.

**Comment by mishinivan** [comment]
Такая же проблема. скрипт копируют из папки icons, но если создашь папку images, даже пустую без файла внутри -  возникает ошибка:
 What went wrong:
Execution failed for task ':parseConfig'.
> config project not found

**Comment by tpsupport** [comment]
@mishinivan Добрый день! 

Пожалуйста, напишите нам на почту, приложив файл конфигурации. Мы всё проверим.
